# Generated by Django 3.2.9 on 2021-12-16 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_auto_20211209_0959'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='qty',
        ),
    ]
